name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    name: Lint, Test & Security
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Verify go.mod tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Build
        run: go build ./...

      - name: Run Tests (with race & coverage)
        run: |
          go test -race -coverprofile=coverage.out ./...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.9.0

      - name: Security Scan (gosec)
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@v2.20.0
          gosec ./...

      - name: Vulnerability Check (govulncheck)
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Docker Build Check
        run: docker build -t payment-service-test .

      - name: Scan Docker Image (Trivy)
        uses: aquasecurity/trivy-action@0.20.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          image-ref: payment-service-test
          format: table
          exit-code: 1
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
